# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "munger"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Chacon", "Brandon Mitchell", "Don Morrison", "Eric Lindvall", "Jeff Wigal"]
  s.date = "2012-05-26"
  s.description = "Reporting engine in Ruby. Forked from Scott Chacon et al."
  s.email = "jeff@assignr.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "examples/column_add.rb",
    "examples/development.log",
    "examples/example_helper.rb",
    "examples/sinatra_app.rb",
    "examples/test.html",
    "lib/munger.rb",
    "lib/munger/data.rb",
    "lib/munger/item.rb",
    "lib/munger/render.rb",
    "lib/munger/render/csv.rb",
    "lib/munger/render/html.rb",
    "lib/munger/render/pdf.rb",
    "lib/munger/render/sortable_html.rb",
    "lib/munger/render/text.rb",
    "lib/munger/report.rb",
    "munger.gemspec",
    "spec/munger/data/new_spec.rb",
    "spec/munger/data_spec.rb",
    "spec/munger/item_spec.rb",
    "spec/munger/render/csv_spec.rb",
    "spec/munger/render/html_spec.rb",
    "spec/munger/render/pdf_spec.rb",
    "spec/munger/render/text_spec.rb",
    "spec/munger/render_spec.rb",
    "spec/munger/report_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jwigal/munger"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Reporting engine in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<prawn>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-hpricot-matchers>, [">= 0"])
      s.add_development_dependency(%q<hpricot>, [">= 0"])
    else
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<prawn>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-hpricot-matchers>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<prawn>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-hpricot-matchers>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
  end
end

